-- SIGTI - Historial de mantenimientos
-- UP: crea una fila por cada intervención realizada sobre un equipo.

BEGIN;

CREATE TABLE IF NOT EXISTS public.maintenances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company VARCHAR(100) NOT NULL DEFAULT 'Petrocasinos'
    CHECK (company IN ('Petrocasinos', 'Cosecharte')),
  last_maintenance DATE NOT NULL DEFAULT CURRENT_DATE,
  equipment_code VARCHAR(20) NOT NULL,
  ip_address VARCHAR(45),
  area VARCHAR(150) NOT NULL,
  responsible VARCHAR(255) NOT NULL,
  brand VARCHAR(100) NOT NULL,
  model VARCHAR(150) NOT NULL,
  serial_number VARCHAR(150) NOT NULL,
  equipment_type VARCHAR(50) NOT NULL
    CHECK (equipment_type IN ('Portátil', 'Torre', 'Todo en Uno')),
  processor_model VARCHAR(150) NOT NULL,
  ram VARCHAR(20) NOT NULL,
  os VARCHAR(100) NOT NULL,
  hdd_size VARCHAR(20),
  ssd_size VARCHAR(20),
  is_nvme BOOLEAN NOT NULL DEFAULT FALSE,
  screen_size VARCHAR(30) NOT NULL,
  antivirus VARCHAR(30) NOT NULL DEFAULT 'Sophos'
    CHECK (antivirus IN ('Sophos', 'Defender')),
  has_glpi BOOLEAN NOT NULL DEFAULT FALSE,
  observations TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.maintenance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  maintenance_id BIGINT NOT NULL
    REFERENCES public.maintenances(id) ON DELETE CASCADE,
  maintenance_date DATE NOT NULL DEFAULT CURRENT_DATE,
  maintenance_type VARCHAR(30),
  technician_id BIGINT
    REFERENCES public.usuarios(id) ON DELETE SET NULL,
  description TEXT NOT NULL,
  actions_taken TEXT,
  observations TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_maintenance_records_maintenance_id
  ON public.maintenance_records(maintenance_id);

CREATE INDEX IF NOT EXISTS idx_maintenance_records_date
  ON public.maintenance_records(maintenance_date DESC);

CREATE INDEX IF NOT EXISTS idx_maintenance_records_technician_id
  ON public.maintenance_records(technician_id);

COMMIT;

-- DOWN (ejecutar únicamente si se requiere revertir esta migración):
-- DROP TABLE IF EXISTS public.maintenance_records;
