-- Catálogo inicial de sedes para los equipos de mantenimiento.
CREATE TABLE IF NOT EXISTS test.sites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company VARCHAR(100) NOT NULL
    CHECK (company IN ('Petrocasinos', 'Cosecharte')),
  name VARCHAR(150) NOT NULL,
  city VARCHAR(150),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (company, name)
);

ALTER TABLE test.sites ENABLE ROW LEVEL SECURITY;

INSERT INTO test.sites (company, name)
VALUES
  ('Petrocasinos', 'Principal'),
  ('Petrocasinos', 'Cantagallo'),
  ('Petrocasinos', 'Velasquez'),
  ('Cosecharte', 'Principal')
ON CONFLICT (company, name) DO NOTHING;

ALTER TABLE test.maintenances
  ADD COLUMN IF NOT EXISTS site_id BIGINT REFERENCES test.sites(id);

GRANT USAGE ON SCHEMA test TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON test.sites TO service_role;
GRANT USAGE, SELECT ON SEQUENCE test.sites_id_seq TO service_role;
