-- Mueve la fuente de autenticación al esquema de pruebas sin perder usuarios ni hashes.
BEGIN;

CREATE TABLE IF NOT EXISTS test.roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS test.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  lastname TEXT,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role_id BIGINT NOT NULL REFERENCES test.roles(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO test.roles (id, name)
SELECT id, name
FROM public.roles
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO test.usuarios (id, name, lastname, username, email, password, role_id, created_at)
SELECT id, name, lastname, username, email, password, role_id, created_at
FROM public.usuarios
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  lastname = EXCLUDED.lastname,
  username = EXCLUDED.username,
  email = EXCLUDED.email,
  password = EXCLUDED.password,
  role_id = EXCLUDED.role_id,
  created_at = EXCLUDED.created_at;

SELECT setval('test.roles_id_seq', COALESCE((SELECT MAX(id) FROM test.roles), 1), true);
SELECT setval('test.usuarios_id_seq', COALESCE((SELECT MAX(id) FROM test.usuarios), 1), true);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'maintenance_records_technician_id_fkey'
      AND conrelid = 'test.maintenance_records'::regclass
  ) THEN
    ALTER TABLE test.maintenance_records
      DROP CONSTRAINT maintenance_records_technician_id_fkey;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'test_maintenance_records_technician_id_fkey'
      AND conrelid = 'test.maintenance_records'::regclass
  ) THEN
    ALTER TABLE test.maintenance_records
      ADD CONSTRAINT test_maintenance_records_technician_id_fkey
      FOREIGN KEY (technician_id)
      REFERENCES test.usuarios(id)
      ON DELETE SET NULL;
  END IF;
END $$;

ALTER TABLE test.roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE test.usuarios ENABLE ROW LEVEL SECURITY;
GRANT USAGE ON SCHEMA test TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON test.roles, test.usuarios TO service_role;
GRANT USAGE, SELECT ON SEQUENCE test.roles_id_seq, test.usuarios_id_seq TO service_role;

COMMIT;
