-- Inventario físico de periféricos por área.
-- No modifica el stock operativo de Sistemas ni las asignaciones activas.
-- Ejecutar una vez en el SQL Editor de Supabase, esquema test.

CREATE TABLE IF NOT EXISTS test.area_peripheral_counts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area TEXT NOT NULL,
  item_type TEXT NOT NULL CHECK (item_type IN ('mouse', 'keyboard', 'charge', 'cooling_base')),
  quantity INTEGER NOT NULL CHECK (quantity >= 0),
  notes TEXT,
  counted_by INTEGER REFERENCES test.usuarios(id) ON DELETE SET NULL,
  counted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT area_peripheral_counts_area_item_type_key UNIQUE (area, item_type)
);

CREATE INDEX IF NOT EXISTS area_peripheral_counts_area_idx
  ON test.area_peripheral_counts (area);

GRANT SELECT, INSERT, UPDATE ON test.area_peripheral_counts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE test.area_peripheral_counts_id_seq TO service_role;
