-- Levantamiento físico de periféricos por puesto de trabajo.
-- Este registro es independiente del stock disponible en Sistemas.

CREATE TABLE IF NOT EXISTS test.equipment_peripheral_counts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id INTEGER NOT NULL REFERENCES test.maintenances(id) ON DELETE CASCADE,
  item_type TEXT NOT NULL CHECK (item_type IN ('mouse', 'keyboard', 'charge', 'cooling_base')),
  quantity INTEGER NOT NULL CHECK (quantity >= 0),
  notes TEXT,
  counted_by INTEGER REFERENCES test.usuarios(id) ON DELETE SET NULL,
  counted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT equipment_peripheral_counts_equipment_item_key UNIQUE (equipment_id, item_type)
);

CREATE INDEX IF NOT EXISTS equipment_peripheral_counts_equipment_idx
  ON test.equipment_peripheral_counts (equipment_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON test.equipment_peripheral_counts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE test.equipment_peripheral_counts_id_seq TO service_role;
