BEGIN;

CREATE TABLE IF NOT EXISTS test.tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  priority VARCHAR(20) NOT NULL DEFAULT 'medium'
    CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  status VARCHAR(30) NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  user_id BIGINT NOT NULL REFERENCES test.usuarios(id) ON DELETE CASCADE,
  technician_id BIGINT REFERENCES test.usuarios(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_test_tickets_user_id ON test.tickets(user_id);
CREATE INDEX IF NOT EXISTS idx_test_tickets_status ON test.tickets(status);

GRANT SELECT, INSERT, UPDATE, DELETE ON test.tickets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE test.tickets_id_seq TO service_role;

COMMIT;
