ALTER TABLE inventory_items
  ADD COLUMN IF NOT EXISTS asset_code VARCHAR(80),
  ADD COLUMN IF NOT EXISTS ip_address VARCHAR(80),
  ADD COLUMN IF NOT EXISTS area VARCHAR(120),
  ADD COLUMN IF NOT EXISTS assigned_user VARCHAR(150),
  ADD COLUMN IF NOT EXISTS equipment_type VARCHAR(40),
  ADD COLUMN IF NOT EXISTS processor VARCHAR(120),
  ADD COLUMN IF NOT EXISTS ram VARCHAR(30),
  ADD COLUMN IF NOT EXISTS operating_system VARCHAR(60),
  ADD COLUMN IF NOT EXISTS hdd VARCHAR(30),
  ADD COLUMN IF NOT EXISTS ssd VARCHAR(30),
  ADD COLUMN IF NOT EXISTS nvme BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS screen_size VARCHAR(40),
  ADD COLUMN IF NOT EXISTS antivirus VARCHAR(40);

CREATE UNIQUE INDEX IF NOT EXISTS idx_inventory_items_asset_code ON inventory_items(asset_code) WHERE asset_code IS NOT NULL;
